version: '3.5'

services:

  service-app1:
    image: nexus.kkbt.dev:8888/app1:1.0
    ports:
      - 6001:80
    deploy:
      mode: global
      # replicas: 3
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure

  service-app2:
    image: nexus.kkbt.dev:8888/app2:1.0
    ports:
      - 6002:80
    deploy:
      mode: global
      # replicas: 3
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure

  service-app3:
    image: nexus.kkbt.dev:8888/app3:1.0
    ports:
      - 6003:80
    deploy:
      mode: global
      # replicas: 3
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure